# Generated by Django 4.0.7 on 2023-01-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('departments', '0002_rename_departament_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('cnpj', models.CharField(max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='categories.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='departments.department')),
            ],
        ),
    ]
