# Generated by Django 4.0.7 on 2023-01-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
