# Generated by Django 4.0.7 on 2023-01-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
