# Generated by Django 4.0.7 on 2023-01-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='supplier',
        ),
    ]
