# Generated by Django 4.0.7 on 2023-01-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='validity',
            field=models.DateField(),
        ),
    ]
