# Generated by Django 4.0.7 on 2023-01-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='supplier',
        ),
    ]
