# Generated by Django 4.0.7 on 2023-01-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_supplier_category_remove_supplier_department'),
        ('categories', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='categories.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='suppliers.supplier'),
            preserve_default=False,
        ),
    ]
