# Generated by Django 4.0.7 on 2023-01-10 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_email_alter_supplier_name'),
        ('contracts', '0003_contract_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='suppliers.supplier'),
        ),
    ]
